version: "3"
services:
  blazegraph:
    image: lyrasis/blazegraph:2.1.5        
    ports:
      - "8889:8080"
      - "8080:8889"
  web:
    # replace username/repo:tag with your name and image details
    image: trnunes/xplain:0.0.1
    command: bundle exec rails server -b 0.0.0.0 -p 3000
    deploy:
      replicas: 1      
      restart_policy:
        condition: on-failure
    ports:
      - "3000:3000"
    networks:
      - webnet
networks:
  webnet:
